run:
  timeout: 5m
linters:
  disable:
    - errcheck
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - gofmt
    - ifshort
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
