run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable:
    - errcheck
    - staticcheck
  enable:
    - gosimple
    - govet
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unused
    
