run:
  timeout: 3m
linters:
  enable:
    - contextcheck
    - durationcheck
    - errname
    - execinquery
    - gofmt
    - ifshort
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
issues:
  exclude-rules:
    - linters:
        - errcheck
      path: '(.+)_test\.go'
    - linters:
        - errcheck
      text: 'Error return value of `(this\.)?migrationContext\.Log\.(Errore|Errorf|Fatal|Fatale|Fatalf|Warning|Warningf)`'
    - linters:
        - errcheck
      text: 'Error return value of `tx.Rollback`'
    - linters:
        - errcheck
      text: 'Error return value of `log\.(Errore|Errorf|Fatal|Fatale|Fatalf|Warning|Warningf)`'
