services:
  mysql-primary:
    image: $TEST_MYSQL_IMAGE
    container_name: mysql-primary
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency=ON
    environment:
      MYSQL_ROOT_PASSWORD: opensesame
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'
  mysql-replica:
    image: $TEST_MYSQL_IMAGE
    container_name: mysql-replica
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency=ON --log-slave-updates=ON
    environment:
      MYSQL_ROOT_PASSWORD: opensesame
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    expose:
      - '3308'
