STOP SLAVE;
RESET SLAVE;
RESET MASTER;

CHANGE MASTER TO MASTER_HOST='primary', MASTER_USER='gh-ost', MASTER_PASSWORD='gh-ost', MASTER_PORT=3306,
  MASTER_AUTO_POSITION=1, MASTER_CONNECT_RETRY=1;

START SLAVE;
SET @@GLOBAL.read_only=ON;
