#!/bin/bash

set -e

. script/bootstrap

mkdir -p bin
bindir="$PWD"/bin
scriptdir="$PWD"/script

# We have a few binaries that we want to build, so let's put them into bin/

RELEASE_VERSION=$(git describe --abbrev=0 --tags | tr -d 'v')
GIT_COMMIT=$(git rev-parse HEAD)

export GOPATH="$PWD/.gopath"
cd .gopath/src/github.com/github/gh-ost

# We put the binaries directly into the bindir, because we have no need for shim wrappers
go build -o "$bindir/gh-ost" -ldflags "-X main.AppVersion=${RELEASE_VERSION} -X main.GitCommit=${GIT_COMMIT}" ./go/cmd/gh-ost/main.go
