#!/bin/bash

set -e

. script/common

echo "Verifying code is formatted via 'gofmt -s -w  go/'"
$DGO gofmt -s -w go
git diff --exit-code --quiet go

if [ "$1" != "fast" ]; then
  ./build.sh -d
fi

echo "Running unit tests"
$DGO go test ./go/...
