#!/bin/bash

set -e

. script/common
# ./build.sh

versions=(
  5.7.21
  5.6.33
)

for mysql_version in "${versions[@]}"; do
  docker build -t gh-ost/dbdeployer:$mysql_version \
    -f docker/dbdeployer/Dockerfile \
    --build-arg MYSQL_VERSION=$mysql_version \
    docker/dbdeployer

  echo "### Running gh-ost tests for $mysql_version"
  if [ $(uname -s) = "Darwin" ]; then
    bin=gh-ost-darwin-amd64
  else
    bin=gh-ost-linux-amd64
  fi
  ./localtests/test-docker.sh -b build/bin/$bin
done
