#!/bin/bash

PREFERRED_GO_VERSION=go1.16.4
SUPPORTED_GO_VERSIONS='go1.1[56]'

GO_PKG_DARWIN=${PREFERRED_GO_VERSION}.darwin-amd64.pkg
GO_PKG_DARWIN_SHA=9f9b940d0f4b3ac764f0a33d78384a87b804aab29d1aacbdc9bca3a3480e9272

GO_PKG_LINUX=${PREFERRED_GO_VERSION}.linux-amd64.tar.gz
GO_PKG_LINUX_SHA=7154e88f5a8047aad4b80ebace58a059e36e7e2e4eb3b383127a28c711b4ff59

export ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd $ROOTDIR

# If Go isn't installed globally, setup environment variables for local install.
if [ -z "$(which go)" ] || [ -z "$(go version | grep "$SUPPORTED_GO_VERSIONS")" ]; then
  GODIR="$ROOTDIR/.vendor/golocal"

  if [ $(uname -s) = "Darwin" ]; then
    export GOROOT="$GODIR/usr/local/go"
  else
    export GOROOT="$GODIR/go"
  fi

  export PATH="$GOROOT/bin:$PATH"
fi

# Check if local install exists, and install otherwise.
if [ -z "$(which go)" ] || [ -z "$(go version | grep "$SUPPORTED_GO_VERSIONS")" ]; then
  [ -d "$GODIR" ] && rm -rf $GODIR
  mkdir -p "$GODIR"
  cd "$GODIR";

  if [ $(uname -s) = "Darwin" ]; then
    curl -L -O https://dl.google.com/go/$GO_PKG_DARWIN
    shasum -a256 $GO_PKG_DARWIN | grep $GO_PKG_DARWIN_SHA
    xar -xf $GO_PKG_DARWIN
    cpio -i < org.golang.go.pkg/Payload
  else
    curl -L -O https://dl.google.com/go/$GO_PKG_LINUX
    shasum -a256 $GO_PKG_LINUX | grep $GO_PKG_LINUX_SHA
    tar xf $GO_PKG_LINUX
  fi

  # Prove we did something right
  echo "$(go version) installed in $GODIR: Go Binary: $(which go)"
else
  echo "$(go version) found in $GODIR: Go Binary: $(which go)"
fi

cd $ROOTDIR

# Configure the new go to be the first go found
export GOPATH=$ROOTDIR/.vendor
