#!/bin/bash

set -e

PREVGOPATH=$GOPATH

. script/bootstrap

mkdir -p bin
bindir="$PWD"/bin

# Put the GOPATH for the user before our fake one so we can run `godep save ./...`
if [ -n "$PREVGOPATH" ]; then
    export GOPATH=$PREVGOPATH:$GOPATH
fi

cd .gopath/src/github.com/github/gh-ost
godep "$@"
