#!/bin/bash

set -e

git clone https://github.com/github/gh-ost-ci-env.git
mkdir -p ~/opt/mysql
mkdir -p ~/sandboxes
gh-ost-ci-env/bin/linux/dbdeployer unpack gh-ost-ci-env/mysql-tarballs/5.7.21.tar.gz --unpack-version=5.7.21

echo '~/sandboxes/rsandbox_5_7_21/m "$@"' >> gh-ost-ci-env/bin/gh-ost-test-mysql-master
echo '~/sandboxes/rsandbox_5_7_21/s1 "$@"' >> gh-ost-ci-env/bin/gh-ost-test-mysql-replica

export PATH="${HOME}/gh-ost-ci-env/bin/:${PATH}"
