#!/bin/bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/util.sh"

# dump environment variables on dirty exit
trap '[[ $? -eq 0 ]] || dump_env' EXIT

set -e

assert_common_envs

# touch file to mark completion of on-before-cut-over hook
touch /tmp/gh-ost-hooks/on-before-cut-over
