#!/bin/bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/util.sh"

# dump environment variables on dirty exit
trap '[[ $? -eq 0 ]] || dump_env' EXIT

set -e

assert_common_envs

assert_env_present "GH_OST_DRAIN_GTID"

# touch file to mark completion of on-success hook
touch /tmp/gh-ost-hooks/on-success
